
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

device_tracker:
- platform: bluetooth_le_tracker

#Quirks for Zigbee Thermostat
zha: 
    custom_quirks_path: /config/config/custom_zha_quirks
    
sensor:
  - platform: template
    sensors:
      is_daytime:
        value_template: "{{ state_attr('sun.sun', 'elevation') > 4 }}"

utility_meter:
  balkon_energy_daily:
    source: sensor.riemannsum_balkonkraftwerk
    cycle: daily
  balkon_energy_monthly:
    source: sensor.riemannsum_balkonkraftwerk
    cycle: monthly
  gesamt_energy:
    source: sensor.riemann_wohnung
    cycle: daily
    tariffs:
      - daylight
      - night
  tages_energy:
    source: sensor.riemann_wohnung
    cycle: daily
    
template:
  - sensor:
      - name: "Total Energy Consumption Day"
        unit_of_measurement: "Wh"
        state_class: total
        device_class: energy
        state: >
          {{ 
            states('sensor.gesamt_energy_daylight') | float(0) 
          }}
  - sensor:
      - name: "Total Energy Consumption Night"
        unit_of_measurement: "Wh"
        state_class: total
        device_class: energy
        state: >
          {{ 
            states('sensor.gesamt_energy_night') | float(0)
          }}
